#!/bin/sh

# 創建必要的目錄
mkdir -p /overlay/upper /overlay/work
mkdir -p /sysroot

# 掛載 OverlayFS
mount -t overlay overlay -o lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work /sysroot

# 掛載其他必要目錄
mount --bind /usr /sysroot/usr

# 切換根檔案系統
exec /usr/bin/systemctl switch-root /sysroot /init
