#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Manager]
#LogLevel=info
#LogTarget=journal
#LogColor=yes
#LogLocation=no
#DumpCore=yes
#CrashShell=no
#ShowStatus=yes
#DefaultStandardOutput=journal
#DefaultStandardError=inherit
#CPUAffinity=1 2
#JoinControllers=cpu,cpuacct net_cls,net_prio
#RuntimeWatchdogSec=0
#ShutdownWatchdogSec=10min
#CapabilityBoundingSet=~CAP_SYS_TIME
#NoNewPrivileges=yes
#SystemCallArchitectures=native
#TimerSlackNSec=50000
#DefaultTimerAccuracySec=1min
#DefaultTimeoutStartSec=90s
#DefaultTimeoutStopSec=90s
#DefaultTimeoutAbortSec=90s
#DefaultRestartSec=100ms
#DefaultStartLimitIntervalSec=10s
#DefaultStartLimitBurst=5
#DefaultEnvironment=
#DefaultLimitCPU=
#DefaultLimitFSIZE=
#DefaultLimitDATA=
#DefaultLimitSTACK=
#DefaultLimitCORE=
#DefaultLimitRSS=
#DefaultLimitNOFILE=1024
#DefaultLimitAS=
#DefaultLimitNPROC=
#DefaultLimitMEMLOCK=
#DefaultLimitLOCKS=
#DefaultLimitSIGPENDING=
#DefaultLimitMSGQUEUE=
#DefaultLimitNICE=0
#DefaultLimitRTPRIO=
#DefaultLimitRTTIME=

# Control group settings
#DefaultMemoryAccounting=no
#DefaultTasksAccounting=no
#DefaultIOAccounting=no

# Allow listing certain controllers for "unified" hierarchy
#Controllers=cpu cpuacct io blkio memory pids

# Manager-wide settings for service startup
#DefaultTasksMax=512
#DefaultTasksMaxSys=2048
#DefaultMemoryLow=0
#DefaultMemoryMin=0
#DefaultIOWeight=100
#DefaultBlockIOWeight=1000
#DefaultCPUAffinity=

# File descriptor storage
#FDStoreMax=512
#DumpWatchdogSec=3min

# System-wide resource limits
#DefaultLimitCPU=infinity
#DefaultLimitFSIZE=infinity
#DefaultLimitDATA=infinity
#DefaultLimitSTACK=infinity
#DefaultLimitCORE=infinity
#DefaultLimitRSS=infinity
#DefaultLimitNOFILE=4096
#DefaultLimitAS=infinity
#DefaultLimitNPROC=4096
#DefaultLimitMEMLOCK=infinity
#DefaultLimitLOCKS=infinity
#DefaultLimitSIGPENDING=4096
#DefaultLimitMSGQUEUE=819200
#DefaultLimitNICE=0
#DefaultLimitRTPRIO=0
#DefaultLimitRTTIME=200000

#ControlGroupKillMode=mixed
#Delegate=no
#CPUAffinity=1 2 3
