#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Manager]
LogLevel=debug
LogTarget=console
DefaultTimeoutStartSec=30s
DefaultTimeoutStopSec=30s
DefaultTasksMax=256
DefaultLimitNOFILE=1024
DefaultLimitNPROC=512
DefaultLimitMEMLOCK=64M
DefaultMemoryAccounting=yes
DefaultTasksAccounting=yes
DefaultIOAccounting=no
#DefaultDependencies=no
